### ISSUE TITLE
Compiler warning CS0659

### ISSUE THREAD

**Issue by Tampa** [gloebit/opensim-moneymodule-gloebit#83]
GloebitSubscription.cs(35,18): warning CS0659: 'GloebitSubscription' overrides Object.Equals(object o) but does not override Object.GetHashCode()

Whether the override is needed or not it produces a compiler warning which should be avoided to sanitize the compiler output making actual problems easier to see.

**Comment by colosi** [comment]
Because the DB truncates the timestamp, I had to change the Object.Equals to also truncate, otherwise the object would fail an equality test after serializing to and back from the DB.  I did not update the hashcode to truncate that.  Adding an override for GetHashCode should fix this warning.

**Comment by Tampa** [comment]
In my current pull request I simply silenced the warning, if an override is needed to ensure functionality then adding one would make sense, but seeing as it is not there I guess it is not needed so silencing the warning is fine.

**Comment by colosi** [comment]
fixed by #87
